stages:
    - build

build:
  stage: build
  image: registry.windmaker.net:5005/a-castellano/limani/base_golang_1_15
  script:
    - git clone https://github.com/a-castellano/backuppc_exporter.git
    - cd backuppc_exporter
    - go get -u github.com/prometheus/client_golang/prometheus
    - go build -o build/backuppc_exporter
  artifacts:
    name: "build"
    paths:
      - build
    expire_in: 10 minutes


